package assets;

public enum GameState {
    Adventure,
    GameIntro,
    QuestIntro,
    HomeMenu,
    Epilogue,

    TownMenu,
    Baker,
    Shop,
    Tanner,
    Noble,
    Tavern,
    Tavern_Drunk,
    Tavern_Drunk_Buy,
    Tavern_Drunk_Steal,
    CrimeBoss,
    CrimeBoss_Buy,
    CrimeBoss_DonationReply,
    Temple,

    Dungeon,
    Dungeon_Entrance,
    Dungeon_Apology,
    Dungeon_KeepStabbing,
    Dungeon_BoneregardChat,
    Dungeon_BoneregardInsult,
    Dungeon_Lich,
    Dungeon_Lich_QuestV1,
    Dungeon_Lich_QuestV2,
    Dungeon_Lich_Attack,
    Dungeon_Lich_Attack_HolyWater,
    Dungeon_Visited,
    Dungeon_Visited_StoleGold,
    Dungeon_Visited_StoleGold_Attack,

    Dragon_Event,
    Dragon_KindaCute,
    Dragon_Date,
    Dragon_Date_Pre,
    Dragon_Date_AttackOnDragon,
    Ambush_Event,
    Ambush_Event_BetrayAmbush,
}
